In [2]:
import pandas as pd

In [3]:
link = pd.read_csv("Dataset/link.csv")
movie = pd.read_csv("Dataset/movie.csv")
rating = pd.read_csv("Dataset/rating.csv")
tag = pd.read_csv("Dataset/tag.csv")
genome_score = pd.read_csv("Dataset/genome_scores.csv")
genome_tag = pd.read_csv("Dataset/genome_tags.csv")

In [6]:
movie["title"].unique()

<StringArray>
[                                      'Toy Story (1995)',
                                         'Jumanji (1995)',
                                'Grumpier Old Men (1995)',
                               'Waiting to Exhale (1995)',
                     'Father of the Bride Part II (1995)',
                                            'Heat (1995)',
                                         'Sabrina (1995)',
                                    'Tom and Huck (1995)',
                                    'Sudden Death (1995)',
                                       'GoldenEye (1995)',
 ...
                               'Ants in the Pants (2000)',
                    'Werner - Gekotzt wird später (2003)',
                                  'Brother Bear 2 (2006)',
                                  'No More School (2000)',
 'Forklift Driver Klaus: The First Day on the Job (2001)',
                           'Kein Bund für's Leben (2007)',
                          'Feuer, Eis & Dosenbier (2002)',
                                     'The Pirates (2014)',
                                    'Rentun Ruusu (2001)',
                                       'Innocence (2014)']
Length: 27262, dtype: str

In [23]:
grouped_tag = tag.groupby("movieId")["tag"].apply(lambda x: " ".join([str(i) for i in set(x) if isinstance(i, str)]))

In [12]:
grouped_tag.shape

(19545,)

In [19]:
genome_tag.shape

(1128, 2)

In [22]:
genome_tag.shape

(1128, 2)

In [24]:
movie.drop_duplicates()
movie.dropna()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy
27275,131258,The Pirates (2014),Adventure
27276,131260,Rentun Ruusu (2001),(no genres listed)
27277,131262,Innocence (2014),Adventure|Fantasy|Horror

In [25]:
grouped_rating = rating.groupby("movieId")["rating"].mean().reset_index()

In [26]:
Dataset = pd.merge(movie, grouped_tag, on="movieId", how="inner")

In [27]:
Dataset.shape

(19545, 4)

In [28]:
Dataset = pd.merge(Dataset, link, on="movieId", how="inner")

In [29]:
Dataset.shape

(19545, 6)

In [30]:
df = pd.merge(Dataset, grouped_rating, on="movieId", how="inner")
df.shape

(19011, 7)

In [31]:
df

,movieId,title,genres,tag,imdbId,tmdbId,rating
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,toy Animation Woody animation light buddy movi...,114709,862.0,3.921240
1,2,Jumanji (1995),Adventure|Children|Fantasy,see also:Zathura bad cgi based on a book not f...,113497,8844.0,3.211977
2,3,Grumpier Old Men (1995),Comedy|Romance,old moldy Jack Lemmon CLV sequel fever sequel ...,113228,15602.0,3.151040
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,CLV characters revenge chick flick,114885,31357.0,2.861393
4,5,Father of the Bride Part II (1995),Comedy,CLV sequel fever Steve Martin sequel Diane Kea...,113041,11862.0,3.064592
...,...,...,...,...,...,...,...
19006,131054,Dinotopia: Quest for the Ruby Sunstone (2005),Children|Fantasy|Sci-Fi,dinosaurs,372238,35177.0,2.000000
19007,131082,Playground (2009),(no genres listed),Yoshitomo Nara documentary,1161051,167161.0,4.500000
19008,131164,Vietnam in HD (2011),War,Vietnam War,2109059,208982.0,4.000000
19009,131170,Parallels (2015),Sci-Fi,alternate reality,3479316,328595.0,3.500000
19010,131258,The Pirates (2014),Adventure,pirates bandits mutiny Korea whale,3485166,285213.0,2.500000

In [38]:
df.to_csv("DataSet.csv", index=False)